
# @name getFolderChildren
Post https://diricodemo1.azurewebsites.net/api/v1/Asset/GetFolders HTTP/1.1
content-type: application/json

{
"UserId":"4551da19-cb68-4172-8f1c-f7693b89c64d",
"CurrentLevelKey":"824be410-75ce-45a5-9824-0b0c761fce11"
}

